ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name='cart'
urlpatterns = [
path('cart/<p>',views.add_to_cart,name="addtocart"),
path('cartview',views.cartview,name="cartview"),
path('removecart/<p>',views.removefromcart,name="removefromcart"),
path('deletcart/<p>',views.deletecart,name="deletecart"),
path('orderform',views.orderform,name="orderform"),
path('orderview',views.orderview,name="orderview")
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include('shop.urls')),
    path("cart/",include('cart.urls')),
    path("search/",include('search.urls')),
]

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name='search'
urlpatterns = [
path('search',views.search,name="search"),
]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
from django.conf import settings
from django.conf.urls.static import static
app_name='shop'


urlpatterns = [
    path("",views.allcategories,name="allcat"),
    path('allproducts/<p>',views.allproducts,name="allproducts"),
    path('details/<d>',views.details,name="details"),
    path('reg/',views.register,name="register"),
    path('log/',views.user_login,name="login"),
    path('logout',views.user_logout,name="logout")
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User
# Create your models here.
class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name
    def subtotal(self):
        return self.quantity*self.product.price

class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    address=models.TextField()
    phone=models.CharField(max_length=30)
    order_status=models.CharField(max_length=20,default="pending")
    delivery_status = models.CharField(max_length=20,default="pending")
    date_ordered= models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username
class Account(models.Model):
    acctnum=models.CharField(max_length=20)
    accttype=models.CharField(max_length=20)
    amount=models.IntegerField()
    def __str__(self):
        return self.acctnum

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/shop/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=200)
    desc=models.TextField()
    image=models.ImageField(upload_to='shop/categories',blank=True,null=True)


class Product(models.Model):
    name = models.CharField(max_length=20)
    desc = models.TextField()
    image = models.ImageField(upload_to='shop/products', blank=True, null=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name

ecommerce/cart/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from shop.models import Product
from cart.models import Cart,Account,Order

# Create your views h
def cartview(request):
    u=request.user
    total=0
    try:
       cart=Cart.objects.filter(user=u)
       for i in cart:
           total+=i.quantity*i.product.price
    except:
        pass

    return render(request,'cart.html',{'c':cart,'total':total})

@login_required
def add_to_cart(request,p):
    d=Product.objects.get(name=p)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=d)
        if(cart.quantity<cart.product.stock):
            cart.quantity+=1
        cart.save()
    except:
        cart=Cart.objects.create(product=d,user=u,quantity=1)
        cart.save()
    return redirect('cart:cartview')

@login_required
def removefromcart(request,p):
    d=Product.objects.get(name=p)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=d)
        if cart.quantity>1:
            cart.quantity-=1
            cart.save()
        else:
            cart.delete()
    except:
        pass
    return redirect('cart:cartview')

def deletecart(request,p):
    d = Product.objects.get(name=p)
    u = request.user
    try:
        cart=Cart.objects.get(user=u,product=d)

        cart.delete()
    except:
        pass
    return redirect('cart:cartview')

def orderform(request):
    if(request.method=="POST"):
        a=request.POST['a']
        p=request.POST['p']
        n=request.POST['n']
        u=request.user
        cart=Cart.objects.filter(user=u)
        #total amount to pay
        total=0
        for i in cart:
            total+=i.quantity*i.product.price
#check whether user has sufficient amount in his/her account to pay the total
        ac=Account.objects.get(acctnum=n)
        if (ac.amount>=total):
            ac.amount=ac.amount-total
            ac.save()

            for i in cart:# create record in order table for each object in cart table for the current user
                o=Order.objects.create(user=u,product=i.product,address=a,phone=p,no_of_items=i.quantity,order_status="paid")
                o.save()
                i.product.stock=i.product.stock-i.quantity
                i.product.save()
            cart.delete()#after ordering, deleting the items from cart for the current user
            msg="order placed successfully"
            return render(request,'orderdetail.html',{'m':msg})

        else:
            msg="Insufficient amount in user account. you cannot place order."
            return render(request, 'orderdetail2.html', {'m': msg})

    return render(request,'orderform.html')
def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u)
    return render(request,'orderview.html',{'o':o})

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
# Create your views here.
def search(request):
    q=""
    product=None
    if(request.method=="POST"):
        q=request.POST['q']
        if q:
            product=Product.objects.filter(Q(name__icontains=q)|Q(desc__icontains=q))
    return render(request,"search.html",{'p':product,'query':q})

ecommerce/shop/views.py
from django.shortcuts import render,redirect
from shop.models import Category,Product
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required


def allcategories(request):
    c = Category.objects.all()
    return render(request,'category.html',{'Category':c})

def allproducts(request,p):
    c=Category.objects.get(name=p)
    p=Product.objects.filter(category=c)
    return render(request,'product.html',{'c':c,'p':p})

def details(request,d):
    p=Product.objects.get(name=d)
    return render(request, 'details.html', {'p':p})

def register(request):
    if (request.method == "POST"):
        u = request.POST['u']
        p = request.POST['p']
        cp = request.POST['cp']
        e = request.POST['e']
        # ph=request.POST['ph']
        # a=request.POST['a']
        if(p==cp):
            u=User.objects.create_user(username=u,password=p,email=e)
            u.save()
            return redirect('shop:allcat')
        else:
            return HttpResponse("PASSWORD NOT MATCHING")
    return render(request,"register.html")
def user_login(request):
    if(request.method=='POST'):
        name=request.POST['n']
        pass1=request.POST['p']
        user=authenticate(username=name,password=pass1)
        if(user):
            login(request,user)
            return redirect('shop:allcat')
        else:
            messages.error(request,"invalid crediatials")


    return render(request,"login.html")
@login_required()
def user_logout(request):
    logout(request)
    return user_login(request)

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Josefin+Slab:wght@500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
<header>
<center><img src="{% static 'images/logo.png' %}" class="mb-1" height="100px" width="80px"></center>
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">GO NOW</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'shop:allcat' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:allproducts' i.name %}">{{i.name}}</a></li>{% endfor %}
          </ul>
            </li>
            {% if user.is_authenticated %}
          {% if user.is_superuser == False %}
          <li class="nav-item">
              <a class="nav-link " aria-current="page" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping" style="font-size:15px;"><sub>{{count}}</sub></i></a>

          <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'cart:orderview' %}">Your orders</a>
        </li>
          {% endif %}
          </li>
         <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'shop:logout' %}">Logout</a>
        </li>
      </ul>
      <form class="d-flex" method="POST" action="{% url 'search:search' %}" style="background-color:black;">
        {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-danger" type="submit">Search</button>
          </form>
          {% else %}
          <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'shop:register' %}">Register</a>
        </li>
         <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'shop:login' %}">Login</a>
        </li>
      {% endif %}
    </div>
  </div>
</nav>
    </header>
{% block content %}
    {% endblock %}

<footer>
  <div class="footer">
<p><i class="fa-solid fa-copyright"></i> GO NOW pvt ltd.All Rights Reserved</p>
    </div>
</footer>
</body>
</html>

ecommerce/templates/cart.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">

{% block content %}
{% if not c %}
<div>
    <h3 class="text-center">Cart is empty</h3>
    <h5 class="text-center text success"><a href="{% url 'shop:allcat' %}">Continue Shopping</a> </h5>
</div>
{% else %}
<div class="container-fluid" style="margin-bottom:50px;">
<div class="row">
    <h2 class="text-center text-primary">SHOPPING CART</h2>
    <div class="col-sm-6 ">
        <table class="table table-bordered">
            <tr><th colspan="5">CART ITEMS</th></tr>
            {% for i in c %}
            <tr>
                <td><img src="{{i.product.image.url}}" height="200px" width="160px"></td>
                <td><b>{{i.product.name}}</b></td>
                <td><b>Product id: {{i.product.id}}</b><br>
                    <b>Unit Price: {{i.product.price}}</b><br>
                    <b>Quantity: {{i.quantity}}*{{i.product.price}}</b></td>
                <td><b>Subtotal: {{i.subtotal}}</b></td>

            <td>
                {% if i.quantity < i.product.stock %}
                <a href="{% url 'cart:addtocart' i.product.name %}"><i class="fa-solid fa-plus" style="color:red;"></i></a>
                <a href="{% url 'cart:removefromcart' i.product.name %}"><i class="fa-solid fa-minus"></i></a><br>
                <a href="{% url 'cart:deletecart' i.product.name %}"><i class="fa-solid fa-trash" style="color:black;"></i></a></td>
                {% else %}
                <a href="{% url 'cart:removefromcart' i.product.name %}"><i class="fa-solid fa-minus"></i></a><br>
                <a href="{% url 'cart:deletecart' i.product.name %}"><i class="fa-solid fa-trash" style="color:black;"></i></a></td>


            </tr>
            {% endif %}
            {% endfor %}
        </table>
    </div>
    <div class="col-sm-4 ">
       <table class="table table-bordered">
            <tr>  <th colspan="4" class="text-center">CHECKOUT</th></tr>
           <tr> <td class="text-center"> <span class="text-primary">TOTAL:  {{total}}</span></td>
          </tr>
       </table>
        <a href="{% url 'cart:orderform' %}" class="btn btn-primary text-light">Place Order</a>
        <a href="{% url 'shop:allcat' %}" class="btn btn-primary text-light"><b>Continue Shopping</b></a>
    </div>
</div>
</div>
{% endif %}
{% endblock %}

ecommerce/templates/category.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
<img src="{% static 'images/gg.png' %}" class="mb-3" height="530px" width="100%">
</div>
<div class="container-fluid mt-4" style="margin-bottom:100px;">
    <h3 class="text-center text-danger">Our Collections</h3>
    <p style="line-height:1.8;text-align:justify; color:white;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>
</div>
<h1 class="text-center" style="color:white;">Categories</h1>
<div class="container mt-4" style="margin-bottom:60px;">
<div class="row">
    <div class="container" style="margin-bottom:100px;">
        <div class="row">
            {% for i in Category %}
            <div class="col-sm-6" style="width:24rem">
                <div class="card">
                    <div class="card-body">
                        <img src="{{i.image.url}}" class="card-img-top" alt="=..." height="250px" width="100%">
                        <h5 class="card-title text-center"><b>{{i.name}}</b></h5>
                        <p class="card-text text-center">{{i.desc}}</p>
                        <a href="{% url 'shop:allproducts' i.name %}" class="btn btn-danger" style="position:relative;left:38%;">PRODUCTS</a>
                    </div>
          </div>
        </div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    {% endfor %}
    </div>
  </div>
{% endblock %}

ecommerce/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-bottom:100px;">
    <div class="row">
        <div class="col-sm-12" style="width:23rem; padding:110px;">
                <img src="{{p.image.url}}" height="300px" width="350px">
        </div>&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;
            <div class="col-sm-12" style="width:25rem; padding:110px;">
                <h1 class="text-center" style="color:white;">{{p.name}}</h1>
                <h2 class="text-center" style="color:white;">{{p.price}}</h2>
                <p class="text-center" style="color:white; text-indent:20px;text-align:justify;">{{p.desc}}</p>
                {% if user.is_superuser == False %}
                {% if p.stock <= 0 %}
                <h2 class="text-danger">Out of Stock</h2>
                {% else %}
                <a href="{% url 'cart:addtocart' p.name  %}" class="btn btn-danger" style="position:relative;left:18%;">ADD TO CART</a>
                {% endif %}

                {% else %}
                {% if p.stock <= 0 %}
                <h2 class="text-danger">Out of Stock</h2>
                <a href="{% url 'admin:index'  %}" class="btn btn-primary" style="position:relative;left:18%;">ADD STOCK</a>
                {% else %}
                <h2 class="text-primary">Product in Stock</h2>
                <a href="{% url 'admin:index'  %}" class="btn btn-primary" style="position:relative;left:18%;">ADD STOCK</a>

                {% endif %}
                 {% endif %}



            </div>
        </div>
        </div>
    </div>
{% endblock %}

ecommerce/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}


{% block content%}

<h1 class="text-primary text-center">Login page</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Username</label>
    <input type="Text" class="form-control" name="n" placeholder="enter the name">
  </div>
    <div class="mb-3">
    <label class="form-label">Password</label>
    <input type="password" class="form-control" name="p" placeholder="enter the password">
  </div>
    <div class="mb-3">
        <label class="form-label">Login </label>
    <input type="submit" class="form-control" >
  </div>

</form>
{% if messages %}
{% for i in messages %}
<ul>
  <li>{{i}}</li>
</ul>
{% endfor %}
{% endif %}


{% endblock %}

ecommerce/templates/orderdetail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">

{% block content %}
<h2 class="text-center  text-light">{{m}}</h2> <br>
<h1><center class="text-light text-large"><i class="fa-solid fa-check-double" style="size:100px;"></i> </center></h1>
{% endblock %}

ecommerce/templates/orderdetail2.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">

{% block content %}
<h2 class="text-center  text-light">{{m}}</h2> <br>
<h1><center class="text-light text-large"><i class="fa-solid fa-face-sad-cry" style="size:100px;"></i></center></h1>
{% endblock %}

ecommerce/templates/orderform.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">

{% block content %}
<div class="container-fluid mt-5" style="margin-bottom:60px;">
<h2 class="text-light">Enter the order details</h2>
<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
    <label class="form-label">Address</label>
    <input type="text" class="form-control" name="a" placeholder="Enter the address">
  </div>
    <div class="mb-3">
    <label class="form-label">Phone</label>
    <input type="text" class="form-control" name="p" placeholder="enter the number">
  </div>
    <div class="mb-3">
        <label class="form-label"> Account Number</label>
    <input type="text" class="form-control" name="n" placeholder="enter the Account number">
  </div>
    <div class="mb-3">
    <input type="submit" class="form-control">
  </div>

</form>
    </div>

{% endblock %}

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-bottom:100px;">
    <h1 class="text-center text-light">Name of the Customer : {{user}}</h1>
{% for i in o %}
    <div class="row">
        <div class="col-sm-12" style="width:23rem; padding:110px;">
                 <img src="{{i.product.image.url}}" height="300px" width="350px">
        </div>&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;
        <div class="col-sm-12" style="width:25rem; padding:110px;">
            <p class="text-center" style="color:white;">Addrss: <b>{{i.address}}</b></p>
                <p class="text-center" style="color:white;">Mob.No:<b>{{i.phone}}</b> </p>
                <p class="text-center" style="color:white; text-indent:20px;text-align:justify;">Product Name: <b> {{i.product.name}}</b></p>
                <p class="text-center" style="color:white; text-indent:20px;text-align:justify;">Date ordered:<b>{{i.date_ordered}}</b> </p>
                <p class="text-center" style="color:white; text-indent:20px;text-align:justify;">Delivery Status:<b>{{i.delivery_status}}</b> </p>
            </div>

        </div>
{% endfor %}
        </div>
{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<div class="container">
<img src="{{c.image.url}}" height="400px" width="900px">
<h1 style="color:white;">{{c.name}}</h1>
<p style="color:white;">{{c.desc}}</p>
    </div>
    </center>
    <div class="container" style="margin-bottom:100px;">
        <div class="row">
            {% for i in p %}
            <div class="col-sm-6" style="width:25rem">
                <div class="card">
                    <div class="card-body">
                        <img src="{{i.image.url}}" class="card-img-top" alt="=..." height="250px" width="100%">
                        <h5 class="card-title text-center" ><b>{{i.name}}</b></h5>
                        <p class="card-text text-center">{{i.price}}</p>
                        <a href="{% url 'shop:details' i.name %}" class="btn btn-danger" style="position:relative;left:38%;">Details</a>
                    </div>
          </div>
        </div>&ensp;
                {% endfor %}
      </div>
    </div>
{% endblock %}

ecommerce/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">

{% block content%}

<h1 class="text-danger text-center ">Register here..</h1>
<form method="POST" style="margin-bottom:80px;">
    {% csrf_token %}
  <div class="mb-3" >
    <label class="form-label">Username </label>
    <input type="Text" class="form-control" name="u" placeholder="enter the name">
  </div>
    <div class="mb-3">
    <label class="form-label">password</label>
    <input type="password" class="form-control" name="p" placeholder="enter the password">
  </div>
    <div class="mb-3">
    <label class="form-label"> confirm password</label>
    <input type="password" class="form-control" name="cp" placeholder="enter the password">
  </div>
    <div class="mb-3">
    <label class="form-label">Email</label>
    <input type="email" class="form-control" name="e" placeholder="enter the email">
  </div>
<!--  <div class="mb-3">-->
<!--    <label class="form-label">phone</label>-->
<!--    <input type="Text" class="form-control" name="ph" placeholder="enter the phonenumder">-->
<!--  </div>-->
<!--  <div class="mb-3">-->
<!--    <label class="form-label">address</label>-->
<!--    <textarea class="form-control" name="a"></textarea>-->
<!--  </div>-->
    <div class="mb-3">
    <input type="submit" class="form-control">
  </div>
</form>


{% endblock %}

ecommerce/templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
    <div class="text-center"><h2 style="color:white;">You Have Searched for <span class="text-danger fw-bolder">{{query}}</span> </h2></div>
</center>
<div class="container mt-2" style="margin-bottom:100px;">
        <div class="row">
            {% for i in p %}
            <div class="col-sm-6" style="width:25rem">
                <div class="card mb-5">
                    <div class="card-body">
                        <img src="{{i.image.url}}" class="card-img-top" alt="=..." height="250px" width="100%">
                        <h5 class="card-title text-center" ><b>{{i.name}}</b></h5>
                        <p class="card-text text-center">{{i.price}}</p>
                        <a href="{% url 'shop:details' i.name %}" class="btn btn-danger" style="position:relative;left:38%;">Details</a>
                    </div>
          </div>
        </div>&ensp;
 {% empty %}
            <h3 class="text-center text-danger">No Search Results Found</h3>
                {% endfor %}
      </div>
    </div>
{% endblock %}